export const allDummyCalenderCells = {
  title: '5th July, Tuesday',
  content: [
    {
      day: 27,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 28,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 29,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 30,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 31,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 1,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 2,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 3,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 4,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 5,
      events: [
        { title: 'Customer Payments Due', color: '#298844', value: '9' },
        { title: 'Customer Payments', color: '#DD5959', value: '2' },
      ],
      thisMonth: true,
      today: true,
    },
    {
      day: 6,
      events: [
        { title: 'Chinese New Year', color: '#8145B1', value: '' },
        { title: 'Customer Payments Due', color: '#298844', value: '9' },
        { title: 'Customer Payments', color: '#DD5959', value: '2' },
      ],
      thisMonth: true,
      today: false,
    },
    {
      day: 7,
      events: [
        { title: 'Customer Payments Due', color: '#298844', value: '9' },
        { title: 'Customer Payments', color: '#DD5959', value: '2' },
      ],
      thisMonth: true,
      today: false,
    },
    {
      day: 8,
      events: [
        { title: 'Chinese New Year', color: '#8145B1', value: '' },
        { title: 'Customer Payments Due', color: '#298844', value: '9' },
        { title: 'Customer Payments', color: '#DD5959', value: '2' },
      ],
      thisMonth: true,
      today: false,
    },
    {
      day: 9,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 10,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 11,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 12,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 13,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 14,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 15,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 16,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 17,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 18,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 19,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 20,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 21,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 22,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 23,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 24,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 25,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 26,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 27,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 28,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 29,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 30,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 1,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 2,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 3,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 4,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 5,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 6,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 7,
      events: [],
      thisMonth: false,
      today: false,
    },
  ],
};
