export const allDummyCalenderCells = {
  title: '5th July, Tuesday',
  content: [
    {
      day: 27,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 28,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 29,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 30,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 31,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 1,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 2,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 3,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 4,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 5,
      events: [
        { title: 'Customer Payments Due', color: '#298844', value: '9' },
        { title: 'Customer Payments', color: '#DD5959', value: '2' },
      ],
      thisMonth: true,
      today: true,
    },
    {
      day: 6,
      events: [
        { title: 'Chinese New Year', color: '#8145B1', value: '' },
        { title: 'Customer Payments Due', color: '#298844', value: '9' },
        { title: 'Customer Payments', color: '#DD5959', value: '2' },
      ],
      thisMonth: true,
      today: false,
    },
    {
      day: 7,
      events: [
        { title: 'Customer Payments Due', color: '#298844', value: '9' },
        { title: 'Customer Payments', color: '#DD5959', value: '2' },
      ],
      thisMonth: true,
      today: false,
    },
    {
      day: 8,
      events: [
        { title: 'Chinese New Year', color: '#8145B1', value: '' },
        { title: 'Customer Payments Due', color: '#298844', value: '9' },
        { title: 'Customer Payments', color: '#DD5959', value: '2' },
      ],
      thisMonth: true,
      today: false,
    },
    {
      day: 9,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 10,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 11,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 12,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 13,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 14,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 15,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 16,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 17,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 18,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 19,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 20,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 21,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 22,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 23,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 24,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 25,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 26,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 27,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 28,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 29,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 30,
      events: [],
      thisMonth: true,
      today: false,
    },
    {
      day: 1,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 2,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 3,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 4,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 5,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 6,
      events: [],
      thisMonth: false,
      today: false,
    },
    {
      day: 7,
      events: [],
      thisMonth: false,
      today: false,
    },
  ],
};

export const dummyCalenderDaydetails = {
  title: '5th July, Tuesday',
  events: [
    {
      title: 'Gaurav Krishna',
      desc: 'Birth Day',
      img: 'https://qph.cf2.quoracdn.net/main-qimg-217015358349186e0e382cb15c5d7c63-lq',
    },
    {
      title: 'International Women’s Day',
      desc: 'Special Day',
      img: '',
    },
  ],
  paymentTobeMade: [
    {
      party: 'Conquer Technologies Pvt Ltd',
      mode: 'Cheque',
      bank: 'HDFC Bank 0045',
      reference: '#00056',
      amount: '256,700.00',
    },
    {
      party: 'Rahul Commerce India Ltd',
      mode: 'Cheque',
      bank: 'HDFC Bank 0045',
      reference: '#00057',
      amount: '334,560.00',
    },
  ],
  paymentTobeCollected: [
    {
      customer_name: 'John Mathew Mathan',
      customer_phone: '9756765453',
      due_date: 'Today',
      invoice_no: 'INV22-0675',
      balance_amount: '256,700.00',
    },
    {
      customer_name: 'SK Ramanaidu',
      customer_phone: '9765676540',
      due_date: 'Today',
      invoice_no: 'INV22-0675',
      balance_amount: '334,560.00',
    },
    {
      customer_name: 'John Mathew Mathan',
      customer_phone: '9343887675',
      due_date: 'Yesterday',
      invoice_no: 'INV22-0675',
      balance_amount: '256,700.00',
    },
    {
      customer_name: 'SK Ramanaidu',
      customer_phone: '9987887676',
      due_date: 'Yesterday',
      invoice_no: 'INV22-0765',
      balance_amount: '334,560.00',
    },
    {
      customer_name: 'John Mathew Mathan',
      customer_phone: '9844455654',
      due_date: '4 Days ago',
      invoice_no: 'INV22-0675',
      balance_amount: '256,700.00',
    },
    {
      customer_name: 'SK Ramanaidu',
      customer_phone: '7503600800',
      due_date: '7 Days ago',
      invoice_no: 'INV22-0765',
      balance_amount: '334,560.00',
    },
    {
      customer_name: 'John Mathew Mathan',
      customer_phone: '7987009889',
      due_date: '42 Days ago',
      invoice_no: 'INV22-0675',
      balance_amount: '256,700.00',
    },
  ],
  accountBalance: 'INR 699,990.00',
  toBePaid: 'INR 591,260.00',
  toBeCollected: 'INR 13,91,260.00',
};
