export const allPumpStatusDummy = [
  {
    id: '1',
    title: 'Gilbaraco [1-1-1]',
    product: 'MS',
    color: '#F7931A',
    sale: '3,400.00',
    qty: '145 Ltr',
    price: '100.37',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
  },
  {
    id: '2',
    title: 'Gilbaraco [1-1-2]',
    product: 'MS',
    color: '#F7931A',
    sale: '3,400.00',
    qty: '145 Ltr',
    price: '100.37',
    isLock: false,
    lockContent: '',
    status: 'SALE END',
  },
  {
    id: '3',
    title: 'Gilbaraco 2-1-1]',
    product: 'HSD 2',
    color: '#1A529B',
    sale: '3,400.00',
    qty: '145 Ltr',
    price: '100.37',
    isLock: false,
    lockContent: '',
    status: 'STOP',
  },
  {
    id: '4',
    title: 'Gilbaraco [2-1-2]',
    product: 'XP95',
    color: '#D073BA',
    sale: '3,400.00',
    qty: '145 Ltr',
    price: '100.37',
    isLock: false,
    lockContent: '',
    status: 'AUTHORISED',
  },
  {
    id: '5',
    title: 'Gilbaraco [2-1-3]',
    product: 'XTRGREEN',
    color: '#03B271',
    sale: '3,400.00',
    qty: '145 Ltr',
    price: '100.37',
    isLock: true,
    lockContent: 'PRESET INTERLOCK 1',
    status: '',
  },
];

export const allNozzleStatusDummy = [
  {
    title: 'Nozzle 1',
    product: 'MS',
    color: '#F7931A',
    isLock: false,
    lockContent: '',
    status: 'FUELING',
    content: 'DU 1/ Pump 1/ Tank 1',
  },
  {
    title: 'Nozzle 2',
    product: 'HSD',
    color: '#1A529B',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
    content: 'DU 1/ Pump 1/ Tank 2',
  },
  {
    title: 'Nozzle 3',
    product: 'MS',
    color: '#F7931A',
    isLock: true,
    lockContent: 'PRESET INTERLOCK',
    status: '',
    content: 'DU 1/ Pump 1/ Tank 2',
  },
  {
    title: 'Nozzle 4',
    product: 'HS',
    color: '#F7931A',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
    content: '',
  },
  {
    title: 'Nozzle 5',
    product: 'HS',
    color: '#F7931A',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
    content: '',
  },
  {
    title: 'Nozzle 6',
    product: 'MS',
    color: '#F7931A',
    isLock: false,
    lockContent: '',
    status: 'SALE END',
    content: 'DU 1/ Pump 1/ Tank 2',
  },
  {
    title: 'Nozzle 7',
    product: 'MS',
    color: '#F7931A',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
    content: 'DU 1/ Pump 1/ Tank 2',
  },
  {
    title: 'Nozzle 8',
    product: 'XP95',
    color: '#D073BA',
    isLock: false,
    lockContent: '',
    status: 'STOP',
    content: 'DU 1/ Pump 1/ Tank 2',
  },
];

export const alertDetailsDummy = {
  paging: {
    page: 1,
    totalItems: 3000,
    showingItemsCount: 10,
    totalPage: 10,
  },
  content: [
    {
      id: '1',
      occurrenceTime: '25 Oct 2022 14:25:36',
      normalizedTime: '25 Oct 2022 15:26:40',
      deviceid: '1',
      device: 'FCC',
      priority: 'High',
      description: 'TT Decantation interlock activated',
    },
    {
      id: '2',
      occurrenceTime: '25 Oct 2022 14:10:48',
      normalizedTime: '25 Oct 2022 15:26:40',
      deviceid: '1',
      device: 'FCC',
      priority: 'High',
      description: 'TT Decantation interlock activated',
    },
    {
      id: '3',
      occurrenceTime: '25 Oct 2022 14:09:12',
      normalizedTime: '25 Oct 2022 15:26:40',
      deviceid: '1',
      device: 'FCC',
      priority: 'High',
      description: 'TT Decantation interlock activated',
    },
  ],
};

export const allAlarmsDummy = {
  total: '300',
  open: '100',
  high: '150',
  low: '50',
};

export const allPriorityDummy = [
  { title: 'Open Alarm', color: '#1149E5', value: 30 },
  { title: 'Low Priority', color: '#FF9933', value: 30 },
  { title: 'High Priority', color: '#B5EACA', value: 40 },
];

export const allEquipmentDummy = [
  { title: 'Open Alarm', color: '#1149E5', value: 30 },
  { title: 'Low Priority', color: '#FF9933', value: 30 },
  { title: 'High Priority', color: '#B5EACA', value: 40 },
];

export const allAlarmTableDemmy = [
  {
    no: '01',
    type: 'Irregular Totaliser Reading ',
    total: '8',
    open: '16',
    highPriority: '58',
    lowPriority: '21',
  },
  {
    no: '02',
    type: 'Totaliser Mismatch',
    total: '8',
    open: '36',
    highPriority: '8',
    lowPriority: '18',
  },
  {
    no: '03',
    type: 'Preset Validation',
    total: '8',
    open: '26',
    highPriority: '8',
    lowPriority: '8',
  },
  {
    no: '04',
    type: 'ATG Probe Communication Failure',
    total: '8',
    open: '6',
    highPriority: '8',
    lowPriority: '8',
  },
  {
    no: '05',
    type: 'Low Level',
    total: '18',
    open: '6',
    highPriority: '18',
    lowPriority: '28',
  },
];

export const alldeviceStatusesDummy = {
  pumpNozzleStatus: {
    total: 9,
    online: 10,
    onlineValue: 34,
    offline: 20,
    offlineValue: 200,
    list: [
      { pump: 'Pump 01', nozzle: 'Nozzle 01', status: 'IDLE' },
      { pump: 'Pump 01', nozzle: 'Nozzle 02', status: 'FUELING' },
      { pump: 'Pump 02', nozzle: 'Nozzle 01', status: 'IDLE' },
      { pump: 'Pump 02', nozzle: 'Nozzle 02', status: 'IDLE' },
      { pump: 'Pump 03', nozzle: 'Nozzle 01', status: 'FUELING' },
      { pump: 'Pump 03', nozzle: 'Nozzle 02', status: 'FUELING' },
      { pump: 'Pump 03', nozzle: 'Nozzle 03', status: 'OFFLINE' },
      { pump: 'Pump 04', nozzle: 'Nozzle 01', status: 'IDLE' },
      { pump: 'Pump 04', nozzle: 'Nozzle 02 ', status: 'OFFLINE' },
    ],
  },
  tankAtgStatus: {
    total: 9,
    online: 10,
    onlineValue: 34,
    offline: 20,
    offlineValue: 200,
    list: [
      { tank: 'Tank 01', atg: 'ATG 01', status: 'ONLINE' },
      { tank: 'Tank 02', atg: 'ATG 02', status: 'ONLINE' },
      { tank: 'Tank 03', atg: 'ATG 03', status: 'ONLINE' },
    ],
  },
  otherDeviceStatus: {
    total: 9,
    online: 10,
    onlineValue: 34,
    offline: 50,
    offlineValue: 200,
    list: [
      { title: 'FCC_ENCLOSUR LOCK  01', status: 'OFFLINE' },
      { title: 'SMPS 01', status: 'OFFLINE' },
      { title: 'SPD 01', status: 'OFFLINE' },
      { title: 'SPD 02', status: 'OFFLINE' },
    ],
  },
  slaveStatus: {
    total: 9,
    online: 10,
    onlineValue: 34,
    offline: 20,
    offlineValue: 200,
    list: [
      { title: 'SLAVE 01', status: 'ONLINE' },
      { title: 'SLAVE 02', status: 'OFFLINE' },
      { title: 'SLAVE 03', status: 'ONLINE' },
    ],
  },
  upsStatus: {
    total: 9,
    online: 10,
    onlineValue: 34,
    offline: 100,
    offlineValue: 200,
    list: [
      { ups: 'UPS 01', status: 'ONLINE' },
      { ups: 'UPS 02', status: 'ONLINE' },
    ],
  },
  integrationStatus: {
    total: 90,
    online: 10,
    onlineValue: 34,
    offline: 0,
    offlineValue: 200,
    list: [
      { title: 'IRAS', status: 'ONLINE' },
      { title: 'IRAS', status: 'ONLINE' },
    ],
  },
};

export const allUpsDummy = [
  {
    title: 'UPS 01',
    status: 'ONLINE',
    charge: 38,
    load: '3.00 %',
    temperature: '33.70 °C ',
    inputFrequency: '50.00 Hz',
    inputVoltage: '229.60 V',
    outputVoltage: '229.80 V',
    batteryVoltage: '13.56 V',
  },
  {
    title: 'UPS 02',
    status: 'OFFLINE',
    charge: 0,
    load: '0.00 %',
    temperature: '26.70 °C ',
    inputFrequency: '50.00 Hz',
    inputVoltage: '00.00 V',
    outputVoltage: '00.00 V',
    batteryVoltage: '13.56 V',
  },
  {
    title: 'UPS 03',
    status: 'ONLINE',
    charge: 5,
    load: '3.00 %',
    temperature: '33.70 °C ',
    inputFrequency: '50.00 Hz',
    inputVoltage: '229.60 V',
    outputVoltage: '229.80 V',
    batteryVoltage: '13.56 V',
  },
  {
    title: 'UPS 04',
    status: 'ONLINE',
    charge: 76,
    load: '0.00 %',
    temperature: '26.70 °C ',
    inputFrequency: '50.00 Hz',
    inputVoltage: '00.00 V',
    outputVoltage: '00.00 V',
    batteryVoltage: '13.56 V',
  },
  {
    title: 'UPS 05',
    status: 'ONLINE',
    charge: 76,
    load: '0.00 %',
    temperature: '26.70 °C ',
    inputFrequency: '50.00 Hz',
    inputVoltage: '00.00 V',
    outputVoltage: '00.00 V',
    batteryVoltage: '13.56 V',
  },
];

export const allTankDummy = [
  {
    title: 'TANK 1',
    product: 'MS',
    productColor: '#FFA113',
    status: 'ONLINE',
    date: '23 06 2022 06:00',
    isLock: false,
    tankQty: 38,
    tankCapacity: '20.000.00 ltr',
    productVolume: '7.559.34 ltr',
    productHeight: '799.42 mm',
    ullageSpace: '12,416.54 ltr',
    waterVolume: '24.11 ltr',
    temperature: '27.40',
    density: '806.90 kg/m^3',
    densityTc: '815.70 kg/m^3',
  },
  {
    title: 'TANK 2',
    product: 'HSD',
    productColor: '#00649E',
    status: 'ONLINE',
    date: '23 06 2022 06:00',
    isLock: false,
    tankQty: 50,
    tankCapacity: '20.000.00 ltr',
    productVolume: '9,9948.86 ltr',
    productHeight: '983.96 mm',
    ullageSpace: '10,025.67 ltr',
    waterVolume: '25.47 ltr',
    temperature: '26.90',
    density: '709.60 kg/m^3',
    densityTc: '720.30 kg/m^3',
  },
  {
    title: 'TANK 3',
    product: 'XP95',
    productColor: '#D073BA',
    status: 'ONLINE',
    date: '23 06 2022 06:00',
    isLock: true,
    tankQty: 50,
    tankCapacity: '20.000.00 ltr',
    productVolume: '9,9948.86 ltr',
    productHeight: '983.96 mm',
    ullageSpace: '10,025.67 ltr',
    waterVolume: '25.47 ltr',
    temperature: '26.90',
    density: '709.60 kg/m^3',
    densityTc: '720.30 kg/m^3',
  },
  {
    title: 'TANK 4',
    product: 'XP95',
    productColor: '#FFA113',
    status: 'OFFLINE',
    date: '23 06 2022 06:00',
    isLock: false,
    tankQty: 50,
    tankCapacity: '20.000.00 ltr',
    productVolume: '9,9948.86 ltr',
    productHeight: '983.96 mm',
    ullageSpace: '10,025.67 ltr',
    waterVolume: '25.47 ltr',
    temperature: '26.90',
    density: '709.60 kg/m^3',
    densityTc: '720.30 kg/m^3',
  },
];
