export const allPumpStatusDummy = [
  {
    id: '1',
    title: 'Gilbaraco [1-1-1]',
    product: 'MS',
    color: '#F7931A',
    sale: '3,400.00',
    qty: '145 Ltr',
    price: '100.37',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
  },
  {
    id: '2',
    title: 'Gilbaraco [1-1-2]',
    product: 'MS',
    color: '#F7931A',
    sale: '3,400.00',
    qty: '145 Ltr',
    price: '100.37',
    isLock: false,
    lockContent: '',
    status: 'STOP',
  },
  {
    id: '3',
    title: 'Gilbaraco 2-1-1]',
    product: 'HSD 2',
    color: '#1A529B',
    sale: '3,400.00',
    qty: '145 Ltr',
    price: '100.37',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
  },
  {
    id: '4',
    title: 'Gilbaraco [2-1-2]',
    product: 'XP95',
    color: '#D073BA',
    sale: '3,400.00',
    qty: '145 Ltr',
    price: '100.37',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
  },
  {
    id: '5',
    title: 'Gilbaraco [2-1-3]',
    product: 'XTRGREEN',
    color: '#03B271',
    sale: '3,400.00',
    qty: '145 Ltr',
    price: '100.37',
    isLock: true,
    lockContent: 'PRESET INTERLOCK 1',
    status: '',
  },
];

export const allNozzleStatusDummy = [
  {
    title: 'Nozzle 1',
    product: 'MS',
    color: '#F7931A',
    isLock: false,
    lockContent: '',
    status: 'FUELING',
    content: 'DU 1/ Pump 1/ Tank 1',
  },
  {
    title: 'Nozzle 2',
    product: 'HSD',
    color: '#1A529B',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
    content: 'DU 1/ Pump 1/ Tank 2',
  },
  {
    title: 'Nozzle 3',
    product: 'MS',
    color: '#F7931A',
    isLock: true,
    lockContent: 'PRESET INTERLOCK',
    status: '',
    content: 'DU 1/ Pump 1/ Tank 2',
  },
  {
    title: 'Nozzle 4',
    product: 'HS',
    color: '#F7931A',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
    content: '',
  },
  {
    title: 'Nozzle 5',
    product: 'HS',
    color: '#F7931A',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
    content: '',
  },
  {
    title: 'Nozzle 6',
    product: 'MS',
    color: '#F7931A',
    isLock: false,
    lockContent: '',
    status: 'SALE END',
    content: 'DU 1/ Pump 1/ Tank 2',
  },
  {
    title: 'Nozzle 7',
    product: 'MS',
    color: '#F7931A',
    isLock: false,
    lockContent: '',
    status: 'IDLE',
    content: 'DU 1/ Pump 1/ Tank 2',
  },
  {
    title: 'Nozzle 8',
    product: 'XP95',
    color: '#D073BA',
    isLock: false,
    lockContent: '',
    status: 'STOP',
    content: 'DU 1/ Pump 1/ Tank 2',
  },
];
