export const dummyExpenseList = {
  paging: {
    page: 1,
    totalItems: 3000,
    showingItemsCount: 10,
    totalPage: 10,
  },
  content: [
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
    {
      invoice: 'EXP22-0032',
      date: '13 APR 2022',
      expenseCategory: 'Electricity & Power',
      expenseDetails: 'Reliance Energy',
      paidFrom: 'Cash in Hand',
      amount: 'INR 4,300.00',
    },
    {
      invoice: 'EXP22-0031',
      date: '13 APR 2022',
      expenseCategory: 'Telephone & Internet',
      expenseDetails: 'Vodafone Idea India Ltd',
      paidFrom: 'HDFC BANK 5266',
      amount: 'INR 2,480.00',
    },
  ],
};
