export const allBAnksDummy = {
  paging: {
    page: 1,
    totalItems: 3000,
    showingItemsCount: 10,
    totalPage: 10,
  },
  content: [
    {
      logo: 'https://cdn.pixabay.com/photo/2014/11/30/14/11/cat-551554_640.jpg',
      name: 'Federal Bank',
      desc: 'This is a sample description',
      mop: 'Cash',
      taxhead: 'GST @ 5% + CESS 12 %',
      category: 'Beverages',
      allowansesIncentives: 'Beverages',
      branch: 'Beverages',
      address: 'Beverages',
      type: 'Beverages',
    },
    {
      logo: 'https://cdn.pixabay.com/photo/2014/11/30/14/11/cat-551554_640.jpg',
      name: 'State bank of India',
      desc: 'This is a sample description',
      mop: 'Checq',
      taxhead: 'GST @ 15% + CESS 12 %',
      category: 'Snaks',
      allowansesIncentives: 'Snaks',
      branch: 'Snaks',
      address: 'Snaks',
      type: 'Snaks',
    },
    {
      logo: 'https://cdn.pixabay.com/photo/2014/11/30/14/11/cat-551554_640.jpg',
      name: 'Canara Bank',
      desc: 'This is a sample description',
      mop: 'UPI',
      taxhead: 'GST @ 10% + CESS 12 %',
      category: 'Tobaco Proects',
      allowansesIncentives: 'Tobaco Proects',
      branch: 'Tobaco Proects',
      address: 'Tobaco Proects',
      type: 'Tobaco Proects',
    },
    {
      logo: 'https://cdn.pixabay.com/photo/2014/11/30/14/11/cat-551554_640.jpg',
      name: 'HDFC',
      desc: 'This is a sample description',
      mop: 'Cash',
      taxhead: 'GST @ 8% + CESS 12 %',
      category: 'Beverages',
      allowansesIncentives: 'Beverages',
      branch: 'Beverages',
      address: 'Beverages',
      type: 'Beverages',
    },
  ],
};

export const allDenominationDummy = [
  { logo: 'lg', value: 'INR 2000' },
  { logo: 'lg', value: 'INR 200' },
  { logo: 'lg', value: 'INR 3000' },
  { logo: 'lg', value: 'INR 400' },
];
